name: Test Action
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Setup Seeker Agent
        uses: ./
        with:
          base-url: 'https://seeker.field-test.blackduck.com'
          project-key: 'hippotech_github' ## must exist in seeker server, or download will get 404
          agent-name: 'test-agent'
          output-path: 'test'
      
      - name: Verify agent was downloaded
        run: |
          if [ -f "test/seeker-agent.jar" ]; then
            echo "✅ Agent downloaded successfully"
            ls -la test/seeker-agent.jar
          else
            echo "❌ Agent not found"
            exit 1
          fi
